#!/usr/bin/env bash

k231 () {
	[ $# -gt 2 ] || {
		echo "# k231 pod myapp-xxxxx-yyy get/describe/..." > /dev/stderr
		return 1
	}
	local type=$1 
	local name=$2 
	local verb=$3 
	shift 3
	if [ $type = "po" ] && [ $verb = "logs" ]
	then
		local fullcmd=(kubectl $verb $name $@) 
	else
		local fullcmd=(kubectl $verb $type/$name $@) 
	fi
	echo "# ${fullcmd[@]}" > /dev/stderr
	${fullcmd[@]}
}

k21 () {
	[ $# -gt 1 ] || {
		echo "# k21 pods get/describe/..." > /dev/stderr
		return 1
	}
	local type=$1
	local verb=$2
	shift 2
	if [ $type = "po" ] && [ $verb = "logs" ]
	then
		local fullcmd=(kubectl $verb $@)
	else
		local fullcmd=(kubectl $verb $type $@)
	fi
	echo "# ${fullcmd[@]}" > /dev/stderr
	${fullcmd[@]}
}


########


